language: ruby
rvm:
  - "2.0.0"
before_script:
  - cp config/.database.travis.yml config/database.yml
  - cp db/seeds.rb.example db/seeds.rb
  - cp config/initializers/secret_token.rb.example config/initializers/secret_token.rb
  - mysql -e 'create database slidecole_test;'
script: RAILS_ENV=test bundle exec rake --trace db:migrate spec
