language: ruby
rvm:
  - "2.0.0"
before_script:
  - cp config/.database.travis.yml config/database.yml
  - mysql -e 'create database slidecole_test;'
script: RAILS_ENV=test bundle exec rake --trace db:migrate spec
